language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script: cd ProcessWrapper
script: python setup.py test --pytest-args="processwrapper --cov processwrapper --pep8 --cov-report term-missing"
after_success: coveralls